word_pair_score = [{'pair': ["cord", "smile"], 'score': 0.02},
                   {'pair': ["hill", "woodland"], 'score': 1.48},
                   {'pair': ["rooster", "voyage"], 'score': 0.04},
                   {'pair': ["car", "journey"], 'score': 1.55},
                   {'pair': ["noon", "string"], 'score': 0.04},
                   {'pair': ["cemetery", "mound"], 'score': 1.69},
                   {'pair': ["fruit", "furnace"], 'score': 0.05},
                   {'pair': ["glass", "jewel"], 'score': 1.78},
                   {'pair': ["autograph", "shore"], 'score': 0.06},
                   {'pair': ["magician", "oracle"], 'score': 1.82},
                   {'pair': ["automobile", "wizard"], 'score': 0.11},
                   {'pair': ["crane", "implement"], 'score': 2.37},
                   {'pair': ["mound", "stove"], 'score': 0.14},
                   {'pair': ["brother", "lad"], 'score': 2.41},
                   {'pair': ["grin", "implement"], 'score': 0.18},
                   {'pair': ["sage", "wizard"], 'score': 2.46},
                   {'pair': ["asylum", "fruit"], 'score': 0.19},
                   {'pair': ["oracle", "sage"], 'score': 2.61},
                   {'pair': ["asylum", "monk"], 'score': 0.39},
                   {'pair': ["bird", "crane"], 'score': 2.63},
                   {'pair': ["graveyard", "madhouse"], 'score': 0.42},
                   {'pair': ["bird", "cock"], 'score': 2.63},
                   {'pair': ["glass", "magician"], 'score': 0.44},
                   {'pair': ["food", "fruit"], 'score': 2.69},
                   {'pair': ["boy", "rooster"], 'score': 0.44},
                   {'pair': ["brother", "monk"], 'score': 2.74},
                   {'pair': ["cushion", "jewel"], 'score': 0.45},
                   {'pair': ["asylum", "madhouse"], 'score': 3.04},
                   {'pair': ["monk", "slave"], 'score': 0.57},
                   {'pair': ["furnace", "stove"], 'score': 3.11},
                   {'pair': ["asylum", "cemetery"], 'score': 0.79},
                   {'pair': ["magician", "wizard"], 'score': 3.21},
                   {'pair': ["coast", "forest"], 'score': 0.85},
                   {'pair': ["hill", "mound"], 'score': 3.29},
                   {'pair': ["grin", "lad"], 'score': 0.88},
                   {'pair': ["cord", "string"], 'score': 3.41},
                   {'pair': ["shore", "woodland"], 'score': 0.90},
                   {'pair': ["glass", "tumbler"], 'score': 3.45},
                   {'pair': ["monk", "oracle"], 'score': 0.91},
                   {'pair': ["grin", "smile"], 'score': 3.46},
                   {'pair': ["boy", "sage"], 'score': 0.96},
                   {'pair': ["serf", "slave"], 'score': 3.46},
                   {'pair': ["automobile", "cushion"], 'score': 0.97},
                   {'pair': ["journey", "voyage"], 'score': 3.58},
                   {'pair': ["mound", "shore"], 'score': 0.97},
                   {'pair': ["autograph", "signature"], 'score': 3.59},
                   {'pair': ["lad", "wizard"], 'score': 0.99},
                   {'pair': ["coast", "shore"], 'score': 3.6},
                   {'pair': ["forest", "graveyard"], 'score': 1.0},
                   {'pair': ["forest", "woodland"], 'score': 3.65},
                   {'pair': ["food", "rooster"], 'score': 1.09},
                   {'pair': ["implement", "tool"], 'score': 3.66},
                   {'pair': ["cemetery", "woodland"], 'score': 1.18},
                   {'pair': ["cock", "rooster"], 'score': 3.68},
                   {'pair': ["shore", "voyage"], 'score': 1.22},
                   {'pair': ["boy", "lad"], 'score': 3.82},
                   {'pair': ["bird", "woodland"], 'score': 1.24},
                   {'pair': ["cushion", "pillow"], 'score': 3.84},
                   {'pair': ["coast", "hill"], 'score': 1.26},
                   {'pair': ["cemetery", "graveyard"], 'score': 3.88},
                   {'pair': ["furnace", "implement"], 'score': 1.37},
                   {'pair': ["automobile", "car"], 'score': 3.92},
                   {'pair': ["crane", "rooster"], 'score': 1.41},
                   {'pair': ["midday", "moon"], 'score': 3.94},
                   {'pair': ["gem", "jewel"], 'score': 3.94}]

P_word_pairs = [each_pair['pair'] for each_pair in word_pair_score]
table_word_set = set([word for word_list in P_word_pairs for word in word_list])

S_word_pair_score = [each_dict['score'] for each_dict in word_pair_score]


